### PR TITLE
Change the output tag from img to object

### PR DESCRIPTION
**Pull request by SebastienAndreo**
With this change we can use hyperlinks capabilty of the svg  and plantuml
an example :

`
{% plantuml %}
actor Bob
actor "[[ {{ site.url }}{% link alice.md %} Alice]]" as Alice
Bob -> Alice [[http://plantuml.com/start]] : hello
note left [[http://plantuml.com/start]]
  a note with a link
end note
{% endplantuml %}
`

With img tag, the hyperlink is not clickable 
```
<html>
    <body>
        <p>
            <object data="8b847b7a3e19b67312cebb77a7e1eeae.svg" type="image/svg+xml"></object>
            <img src="8b847b7a3e19b67312cebb77a7e1eeae.svg" alt="PLant UML SVG DIAg" class="plantuml"/>
        </p>

    </body>
</html>
```

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@SebastienAndreo this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `1.3.4`

**Comment by 0crat** [comment]
Job `gh:yegor256/jekyll-plantuml#14` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
